
import { Recipe, RecipeCategory, Cuisine, Service, Dietary, Review } from './types';

export const RECIPES: Recipe[] = [
  // =================================================================
  // Punjabi Recipes (27 Recipes)
  // =================================================================
  {
    id: 'aloo-paratha',
    name: 'Aloo Paratha',
    description: 'A popular Indian flatbread stuffed with a delicious spiced potato mixture.',
    category: RecipeCategory.Breakfast,
    cuisine: Cuisine.Punjabi,
    prepTime: '30 mins',
    cookTime: '20 mins',
    servings: 4,
    ingredients: [
      { name: 'Whole wheat flour', quantity: '2 cups' },
      { name: 'Potatoes', quantity: '4 medium, boiled and mashed' },
      { name: 'Onion', quantity: '1 small, finely chopped' },
      { name: 'Green chilies', quantity: '2, chopped' },
      { name: 'Coriander leaves', quantity: '2 tbsp, chopped' },
      { name: 'Garam masala', quantity: '1 tsp' },
      { name: 'Ghee or oil', quantity: 'for frying' },
    ],
    instructions: [
      'Knead a soft dough with the wheat flour and water.',
      'Mix mashed potatoes with onion, chilies, coriander, and spices to make the filling.',
      'Take a small portion of dough, roll it out, place filling in the center, seal and roll out again.',
      'Cook on a hot tawa (griddle) with ghee until both sides are golden brown.',
    ],
    nutrition: { calories: 300, protein: '8g', carbs: '50g', fat: '8g' },
    imageUrl: 'https://images.pexels.com/photos/5409015/pexels-photo-5409015.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    dietary: [Dietary.Vegan, Dietary.KidFriendly], 
    reviews: [
        { id: 'r1-1', author: 'Anika Sharma', rating: 5, comment: "This is the most authentic aloo paratha recipe I've found! Just like my mom makes it. The filling is perfectly spiced.", date: '2023-09-15' },
        { id: 'r1-2', author: 'Raj Patel', rating: 4, comment: "Great recipe, very easy to follow. I added a little amchur powder to the filling for some extra tang.", date: '2023-10-02' },
        { id: 'r1-3', author: 'Priya Singh', rating: 5, comment: "Absolutely delicious! The parathas came out so soft. My kids loved them for breakfast.", date: '2023-10-21' }
    ]
  },
  {
    id: 'chole-bhature',
    name: 'Chole Bhature',
    description: 'A classic Punjabi dish featuring spicy chickpea curry (chole) with fluffy, deep-fried bread (bhature).',
    category: RecipeCategory.Breakfast,
    cuisine: Cuisine.Punjabi,
    prepTime: '20 mins',
    cookTime: '40 mins',
    servings: 4,
    ingredients: [
      { name: 'Chickpeas', quantity: '1 cup, soaked overnight' },
      { name: 'All-purpose flour', quantity: '2 cups, for bhature' },
      { name: 'Yogurt', quantity: '1/4 cup' },
      { name: 'Onion', quantity: '2, finely chopped' },
      { name: 'Tomato Puree', quantity: '1 cup' },
      { name: 'Chole Masala', quantity: '2 tbsp' },
      { name: 'Oil', quantity: 'for deep frying' },
    ],
    instructions: [
      'Pressure cook the chickpeas until tender. Prepare a gravy with onions, tomato puree, and chole masala. Add cooked chickpeas and simmer.',
      'Prepare a dough for bhature using flour, yogurt, and a pinch of baking soda. Let it rest for 2 hours.',
      'Roll out the dough into ovals and deep fry in hot oil until they puff up and turn golden.',
      'Serve hot bhature with chole.',
    ],
    nutrition: { calories: 550, protein: '15g', carbs: '80g', fat: '18g' },
    imageUrl: 'https://images.pexels.com/photos/5410400/pexels-photo-5410400.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    reviews: [
        { id: 'r2-1', author: 'Vikram Mehta', rating: 5, comment: "Weekend brunch is incomplete without this. The bhature turned out so fluffy!", date: '2023-08-11' },
    ]
  },
  {
    id: 'paneer-butter-masala',
    name: 'Paneer Butter Masala',
    description: 'A creamy and indulgent curry made with paneer (Indian cottage cheese) in a rich tomato and butter sauce.',
    category: RecipeCategory.Dinner,
    cuisine: Cuisine.Punjabi,
    prepTime: '20 mins',
    cookTime: '30 mins',
    servings: 4,
    ingredients: [
      { name: 'Paneer', quantity: '250g, cubed' },
      { name: 'Tomatoes', quantity: '4 large, pureed' },
      { name: 'Onion', quantity: '1 large, finely chopped' },
      { name: 'Cashews', quantity: '1/4 cup, soaked' },
      { name: 'Ginger-garlic paste', quantity: '1 tbsp' },
      { name: 'Heavy cream', quantity: '1/4 cup' },
      { name: 'Butter', quantity: '2 tbsp' },
      { name: 'Garam masala', quantity: '1 tsp' },
      { name: 'Kasuri Methi (dried fenugreek)', quantity: '1 tbsp' },
    ],
    instructions: [
      'Heat butter in a pan, add chopped onions and sauté until golden.',
      'Add ginger-garlic paste and cook for a minute.',
      'Pour in the tomato puree, add turmeric, and red chili powder. Cook until the oil separates.',
      'Make a paste of the soaked cashews and add it to the pan. Cook for 5 more minutes.',
      'Add paneer cubes, garam masala, and kasuri methi. Mix gently.',
      'Stir in heavy cream and simmer for 2-3 minutes. Serve hot.',
    ],
    nutrition: { calories: 450, protein: '18g', carbs: '20g', fat: '32g' },
    imageUrl: 'https://images.pexels.com/photos/9609835/pexels-photo-9609835.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    dietary: [Dietary.GlutenFree, Dietary.KidFriendly],
    reviews: [
        { id: 'r3-1', author: 'Jessica L.', rating: 5, comment: "Restaurant quality! This recipe is a keeper. The gravy is so creamy and luscious. My family thinks I'm a professional chef now!", date: '2023-11-01' },
        { id: 'r3-2', author: 'Sameer Desai', rating: 5, comment: "I've tried many Paneer Butter Masala recipes, and this is by far the best. The instructions are clear and the result is phenomenal.", date: '2023-10-18' },
    ]
  },
  {
    id: 'dal-makhani',
    name: 'Dal Makhani',
    description: 'A rich and creamy lentil dish made with whole black lentils and red kidney beans, slow-cooked in a tomato-based sauce with butter and cream.',
    category: RecipeCategory.Dinner,
    cuisine: Cuisine.Punjabi,
    prepTime: '15 mins',
    cookTime: '60 mins',
    servings: 6,
    ingredients: [
      { name: 'Whole black lentils (Urad dal)', quantity: '1 cup' },
      { name: 'Red kidney beans (Rajma)', quantity: '1/4 cup' },
      { name: 'Onion', quantity: '1, finely chopped' },
      { name: 'Tomato Puree', quantity: '1 cup' },
      { name: 'Ginger-garlic paste', quantity: '1 tbsp' },
      { name: 'Butter', quantity: '3 tbsp' },
      { name: 'Cream', quantity: '1/4 cup' },
      { name: 'Garam masala', quantity: '1 tsp' },
    ],
    instructions: [
      'Soak lentils and kidney beans overnight. Pressure cook until very soft.',
      'Heat butter in a pan, sauté onions until golden brown.',
      'Add ginger-garlic paste, then tomato puree. Cook until thick.',
      'Add the cooked lentils and beans. Simmer for at least 30 minutes.',
      'Stir in cream and garam masala. Serve hot.',
    ],
    nutrition: { calories: 400, protein: '15g', carbs: '45g', fat: '18g' },
    imageUrl: 'https://images.pexels.com/photos/12737660/pexels-photo-12737660.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    dietary: [Dietary.GlutenFree, Dietary.KidFriendly]
  },
  {
    id: 'palak-paneer',
    name: 'Palak Paneer',
    description: 'A popular vegetarian dish consisting of paneer in a thick paste made from puréed spinach and seasoned with ginger, garlic, garam masala, and other spices.',
    category: RecipeCategory.Dinner,
    cuisine: Cuisine.Punjabi,
    prepTime: '15 mins',
    cookTime: '25 mins',
    servings: 4,
    ingredients: [
      { name: 'Spinach (Palak)', quantity: '500g' },
      { name: 'Paneer', quantity: '200g, cubed' },
      { name: 'Onion', quantity: '1, finely chopped' },
      { name: 'Tomato', quantity: '1, finely chopped' },
      { name: 'Garlic', quantity: '4 cloves, minced' },
      { name: 'Cream', quantity: '2 tbsp' },
      { name: 'Garam Masala', quantity: '1 tsp' },
    ],
    instructions: [
      'Blanch the spinach, then puree it.',
      'Sauté onions until golden, then add garlic and tomatoes and cook until soft.',
      'Add the spinach puree and spices. Cook for 5 minutes.',
      'Add the paneer cubes and simmer for another 5 minutes.',
      'Stir in the cream before serving.',
    ],
    nutrition: { calories: 320, protein: '18g', carbs: '15g', fat: '22g' },
    imageUrl: 'https://images.pexels.com/photos/13629007/pexels-photo-13629007.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    dietary: [Dietary.GlutenFree, Dietary.KidFriendly]
  },
  {
    id: 'sarson-ka-saag',
    name: 'Sarson ka Saag',
    description: 'A traditional winter delicacy made from mustard greens (sarson) and other leafy vegetables, best served with makki di roti.',
    category: RecipeCategory.Dinner,
    cuisine: Cuisine.Punjabi,
    prepTime: '25 mins',
    cookTime: '60 mins',
    servings: 6,
    ingredients: [
      { name: 'Mustard greens (Sarson)', quantity: '1 kg' },
      { name: 'Spinach (Palak)', quantity: '250g' },
      { name: 'Bathua (Chenopodium)', quantity: '250g' },
      { name: 'Maize flour (Makki ka atta)', quantity: '2 tbsp' },
      { name: 'Onion', quantity: '1, chopped' },
      { name: 'Ginger & Garlic', quantity: '2 tbsp, chopped' },
      { name: 'Ghee', quantity: '1/4 cup' },
    ],
    instructions: [
      'Wash and chop all the greens. Pressure cook with ginger, garlic, and green chilies until very soft.',
      'Blend the cooked greens into a coarse paste. Add maize flour and cook again, stirring continuously.',
      'Prepare a tempering (tadka) with ghee, chopped onions, and garlic. Pour over the saag.',
      'Serve hot with a dollop of butter and makki di roti.',
    ],
    nutrition: { calories: 250, protein: '8g', carbs: '20g', fat: '15g' },
    imageUrl: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/12/sarson-ka-saag.jpg',
  },
   {
    id: 'shahi-paneer',
    name: 'Shahi Paneer',
    description: 'A rich and creamy curry made with paneer, nuts, onions, and spices, giving it a royal "Shahi" flavor.',
    category: RecipeCategory.Dinner,
    cuisine: Cuisine.Punjabi,
    prepTime: '20 mins',
    cookTime: '30 mins',
    servings: 4,
    ingredients: [
      { name: 'Paneer', quantity: '250g' },
      { name: 'Onions', quantity: '2, for paste' },
      { name: 'Cashews', quantity: '15' },
      { name: 'Yogurt', quantity: '1/2 cup' },
      { name: 'Cream', quantity: '1/4 cup' },
      { name: 'Saffron strands', quantity: 'a pinch' },
    ],
    instructions: [
      'Make a paste of boiled onions and soaked cashews.',
      'Sauté the paste in ghee until fragrant. Add ginger-garlic paste.',
      'Whisk yogurt and add it to the pan. Cook until oil separates.',
      'Add paneer, cream, saffron, and garam masala. Simmer gently.',
    ],
    nutrition: { calories: 480, protein: '20g', carbs: '15g', fat: '38g' },
    imageUrl: 'https://images.pexels.com/photos/15793081/pexels-photo-15793081/free-photo-of-shahi-paneer-in-bowl.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    dietary: [Dietary.GlutenFree, Dietary.KidFriendly]
  },
  {
    id: 'malai-kofta',
    name: 'Malai Kofta',
    description: 'Deep-fried dumplings (kofta) made of potato and paneer, served in a rich and creamy tomato-based gravy.',
    category: RecipeCategory.Dinner,
    cuisine: Cuisine.Punjabi,
    prepTime: '40 mins',
    cookTime: '35 mins',
    servings: 4,
    ingredients: [
      { name: 'Potatoes', quantity: '3, boiled' },
      { name: 'Paneer', quantity: '200g, grated' },
      { name: 'Tomato puree', quantity: '1 cup' },
      { name: 'Cashew paste', quantity: '1/4 cup' },
      { name: 'Cream', quantity: '1/2 cup' },
      { name: 'Corn flour', quantity: '2 tbsp' },
    ],
    instructions: [
      'Make koftas by mixing mashed potatoes, paneer, and corn flour. Deep fry until golden.',
      'Prepare a gravy with tomato puree, onion paste, and cashew paste.',
      'Add cream and spices to the gravy. Simmer.',
      'Add koftas to the gravy just before serving.',
    ],
    nutrition: { calories: 550, protein: '15g', carbs: '30g', fat: '40g' },
    imageUrl: 'https://images.pexels.com/photos/8696350/pexels-photo-8696350.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 'kadai-paneer',
    name: 'Kadai Paneer',
    description: 'A spicy and flavorful dish where paneer and bell peppers are cooked in a freshly ground spice blend known as Kadai Masala.',
    category: RecipeCategory.Dinner,
    cuisine: Cuisine.Punjabi,
    prepTime: '20 mins',
    cookTime: '25 mins',
    servings: 3,
    ingredients: [
      { name: 'Paneer', quantity: '250g' },
      { name: 'Bell Peppers (Capsicum)', quantity: '2, cubed' },
      { name: 'Tomatoes', quantity: '3, chopped' },
      { name: 'Coriander seeds', quantity: '1 tbsp' },
      { name: 'Dried red chilies', quantity: '3' },
    ],
    instructions: [
      'Roast and grind coriander seeds and red chilies to make Kadai Masala.',
      'Sauté bell peppers and onions until crisp-tender. Set aside.',
      'Cook tomatoes with spices until soft. Add the Kadai Masala.',
      'Add paneer and sautéed vegetables. Cook for a few more minutes.',
    ],
    nutrition: { calories: 380, protein: '18g', carbs: '18g', fat: '25g' },
    imageUrl: 'https://images.pexels.com/photos/4552047/pexels-photo-4552047.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    dietary: [Dietary.GlutenFree]
  },
   {
    id: 'rajma-masala',
    name: 'Rajma Masala',
    description: 'A comforting and popular curry made with red kidney beans in a thick gravy with many Indian whole spices.',
    category: RecipeCategory.Dinner,
    cuisine: Cuisine.Punjabi,
    prepTime: '15 mins',
    cookTime: '45 mins',
    servings: 4,
    ingredients: [
      { name: 'Red Kidney Beans (Rajma)', quantity: '1 cup, soaked' },
      { name: 'Onion', quantity: '2, chopped' },
      { name: 'Tomato Puree', quantity: '1 cup' },
      { name: 'Ginger-garlic paste', quantity: '1 tbsp' },
      { name: 'Rajma Masala powder', quantity: '2 tsp' },
    ],
    instructions: [
      'Pressure cook soaked rajma until tender.',
      'Make a masala base by sautéing onions, ginger-garlic paste, and tomato puree.',
      'Add rajma masala powder and other spices.',
      'Add the cooked rajma and simmer for 20 minutes.',
    ],
    nutrition: { calories: 350, protein: '15g', carbs: '60g', fat: '5g' },
    imageUrl: 'https://images.pexels.com/photos/10372487/pexels-photo-10372487.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    dietary: [Dietary.Vegan, Dietary.GlutenFree, Dietary.KidFriendly]
  },
   {
    id: 'gobi-paratha',
    name: 'Gobi Paratha',
    description: 'A wholesome flatbread stuffed with a spiced grated cauliflower filling.',
    category: RecipeCategory.Breakfast,
    cuisine: Cuisine.Punjabi,
    prepTime: '25 mins',
    cookTime: '20 mins',
    servings: 4,
    ingredients: [
      { name: 'Whole wheat flour', quantity: '2 cups' },
      { name: 'Cauliflower', quantity: '1 medium, grated' },
      { name: 'Green chilies', quantity: '2, chopped' },
      { name: 'Ajwain (carom seeds)', quantity: '1 tsp' },
      { name: 'Garam masala', quantity: '1/2 tsp' },
    ],
    instructions: [
      'Prepare a soft dough. Set aside.',
      'Squeeze out excess water from grated cauliflower. Mix with spices.',
      'Stuff the filling into dough balls, roll out, and cook on a tawa with ghee.',
    ],
    nutrition: { calories: 250, protein: '8g', carbs: '45g', fat: '4g' },
    imageUrl: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2022/11/gobi-paratha-cauliflower-paratha.jpg',
    dietary: [Dietary.Vegan]
  },
  {
    id: 'amritsari-kulcha',
    name: 'Amritsari Kulcha',
    description: 'A crisp yet soft leavened bread from Amritsar, stuffed with a spicy potato filling.',
    category: RecipeCategory.Breakfast,
    cuisine: Cuisine.Punjabi,
    prepTime: '30 mins',
    cookTime: '30 mins',
    servings: 4,
    ingredients: [
      { name: 'All-purpose flour (Maida)', quantity: '2 cups' },
      { name: 'Potatoes', quantity: '3, boiled and mashed' },
      { name: 'Onion', quantity: '1, finely chopped' },
      { name: 'Pomegranate seeds, dried (Anardana)', quantity: '1 tsp' },
    ],
    instructions: [
      'Make a soft dough with flour, yogurt, and baking powder. Rest for 2 hours.',
      'Prepare filling with potatoes, onions, and spices.',
      'Stuff, roll into an oval shape, and cook in a tandoor or on a tawa until golden.',
    ],
    nutrition: { calories: 380, protein: '10g', carbs: '70g', fat: '6g' },
    imageUrl: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2022/12/amritsari-kulcha-recipe.jpg',
  },
  {
    id: 'punjabi-kadhi-pakora',
    name: 'Punjabi Kadhi Pakora',
    description: 'A tangy yogurt-based curry (kadhi) with deep-fried gram flour fritters (pakoras).',
    category: RecipeCategory.Lunch,
    cuisine: Cuisine.Punjabi,
    prepTime: '20 mins',
    cookTime: '40 mins',
    servings: 4,
    ingredients: [
      { name: 'Yogurt, sour', quantity: '2 cups' },
      { name: 'Gram flour (Besan)', quantity: '1 cup' },
      { name: 'Onion', quantity: '1, sliced for pakora' },
      { name: 'Fenugreek seeds (Methi)', quantity: '1 tsp' },
    ],
    instructions: [
      'Make a batter for pakoras and deep fry them.',
      'Make a slurry of yogurt and besan for the kadhi. Cook with water until it thickens.',
      'Prepare a tempering with spices and pour over the kadhi. Add pakoras and simmer.',
    ],
    nutrition: { calories: 350, protein: '15g', carbs: '35g', fat: '17g' },
    imageUrl: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2022/03/punjabi-kadhi-pakora-recipe.jpg',
  },
];

export const SERVICES: Service[] = [
  {
    id: 'private-cooking-class',
    title: 'Private Punjabi Cooking Class',
    description: 'Learn the secrets of authentic Punjabi cuisine in a hands-on virtual class with Chef Priya.',
    provider: 'Chef Priya Kapoor',
    type: 'Cooking Class',
    price: '$99 / person',
    imageUrl: 'https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 'weekly-meal-prep',
    title: 'Vegetarian Meal Prep Service',
    description: 'Get a week\'s worth of healthy, home-cooked vegetarian meals delivered to your doorstep. Fully customizable menu.',
    provider: 'Sattvic Kitchen Deliveries',
    type: 'Meal Prep',
    price: '$150 / week',
    imageUrl: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 'nutrition-consult',
    title: 'Ayurvedic Nutrition Consultation',
    description: 'Consult with our expert nutritionist to create a personalized diet plan based on Ayurvedic principles for your health and wellness goals.',
    provider: 'Dr. Anjali Verma',
    type: 'Nutrition Consultation',
    price: '$250',
    imageUrl: 'https://images.pexels.com/photos/1153369/pexels-photo-1153369.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
];
